name: Playwright tests via Docker

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${ { secrets.BASE_URL } }
      HTTP_CREDENTIALS_USERNAME: ${ { secrets.HTTP_CREDENTIALS_USERNAME } }
      HTTP_CREDENTIALS_PASSWORD: ${ { secrets.HTTP_CREDENTIALS_PASSWORD } }
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false # Set to true if you want to push the image to a container registry
          tags: your-image-tag:latest

      - name: Run tests
        run: |
          docker run playwright test:latest
